### ISSUE TITLE
Support class attribute definition order

### ISSUE THREAD

**Issue by ceball** [pyviz/param#185]
Currently we have precedence.

Python>=3.6: preserves class attribute definition order.

3.6>Python>=3: allows an OrderedDict to be used for class dict.

Python 2: we would continue supporting precedence (which in python 3 could still be used to override class attribute definition order). Unless we were to do some kind of inspect-the-source hack...

**Comment by jbednar** [comment]
We should always support precedence, even if the class dict is ordered, because there's no other way to sort parameters defined across different levels of a class hierarchy that I know of.  But assuming each lower level of the hierarchy adds to the end of the ordered dictionary, defining them in hierarchy order by default isn't a bad arrangement anyway, as the lowest ones in the hierarchy will be the most specific, and vice versa.

**Comment by ceball** [comment]
Right, I wasn't clear in the last paragraph: precedence would continue to be supported, even if supporting class attribute definition order could also be done in python 2.

I'm not sure if your default ordering is the same as mine, though: I would expect the most specific parameters to appear first i.e. first the current class's parameters in the order they were declared, then its parent's parameters in the order declared in that class, etc.

(Although I can never remember if precedence is defined the way round I expect, or the wrong way round, and I end up double guessing and then never being able to remember which round it is!)

**Comment by jbednar** [comment]
I agree, most specific would be first, which does mean *reverse* class definition order.

**Comment by jlstevens** [comment]
By the way, this already works! See what was done in https://github.com/pyviz/panel/pull/238.

Perhaps all param needs here are docs to describe this behavior and the Python versions that can be trusted and then this issue can be closed?

**Comment by jbednar** [comment]
Sounds good!  Note that it's actually in order by least specific, but I think that's also ok, and is actually better when switching between object types.  E.g. if the parent class defines x,y shared across all subclasses, it's good to have x,y first if you switch various subclass types in and out, to emphasize that commonality and allow the novel bits to stand out.  So I think the current behavior is good, once it's documented. But I'll close this issue, having added a link to it from the main needs-docs issue (#313).
