### ISSUE TITLE
The word 'precedence' is too long

### ISSUE THREAD

**Issue by jlstevens** [pyviz/param#311]
This is particularly annoying when using panel. It would be good to have a shorter alias.

Some quick suggestions: rank, order, priority

I am also curious whether the newly sorted behavior of dictionaries in recent Python 3 might mean we can access the order of parameter definition in the class. If that were true, we could avoid needing to use this argument altogether.

**Comment by jbednar** [comment]
I agree; "precedence" is too long. If I abbreviate Param as `pm`, if I want the widgets to be ordered the parameter declarations are now completely dominated by "precedence", the least important thing about them:

```
class Explorer(pm.Parameterized):
    plot          = pm.ObjectSelector( precedence=0.10, default=source.plots[0], objects=plots)
    normalization = pm.ObjectSelector( precedence=0.12, default='eq_hist',       objects=norms)
    cmap          = pm.ObjectSelector( precedence=0.14, default=cmaps['fire'],   objects=cmaps)
    spreading     = pm.Integer(        precedence=0.16, default=0, bounds=(0, 5))
    
    basemap       = pm.ObjectSelector( precedence=0.18, default=bases['EsriImagery'], objects=bases)
    data_opacity  = pm.Magnitude(      precedence=0.20, default=1.00, doc="Alpha value for the data")
    map_opacity   = pm.Magnitude(      precedence=0.22, default=0.75, doc="Alpha value for the map")
    show_labels   = pm.Boolean(        precedence=0.24, default=True)
```

"Priority" isn't much shorter. "Rank" is nice and short, and "order" is fairly short.  There's also "sort".  I don't have much preference between any of those.

Alternatively, it would be great if we could use the parameter definition order by default; that would make it work much more reasonably in most cases.

**Comment by jbednar** [comment]
It's still annoying that precedence is so long, but now that https://github.com/pyviz/param/issues/185 establishes clear guidelines for when we don't need precedence, let's close this issue.  If someone wants to add a `rank` alias at some point, go for it!
