### ISSUE TITLE
Class inheritance ordering

### ISSUE THREAD

**Issue by RodrigoNeves95** [pyviz/param#335]
```python

import param
import pandas as pd

class Test1(param.Parameterized):
    param_a = param.ListSelector()
    
class Test2(param.Parameterized):
    param_b = param.ListSelector()

class A(Test1):
    def __init__(self):
        self.param.param_a.default = ['dummy_a']
        self.param.param_a.objects = ['dummy_a']
        
        Test1.__init__(self)
        
    def dashboard(self):
        return pd.DataFrame([0])

class B(Test2):
    def __init__(self):
        self.param.param_b.default = ['dummy_b']
        self.param.param_b.objects = ['dummy_b']

        Test2.__init__(self)
        
    def dashboard(self):
        return pd.DataFrame([0])
    
class C(A, B):
    def __init__(self):
        A.__init__(self)
        B.__init__(self)
        
    def dashboard(self, **kwargs):
        return pd.DataFrame([0])
    
plot = C()

print(plot.param_a)
print(plot.param_b)
print('----'*10)
a = A()
print(a.param_a)
print('----'*10)
b = B()
print(b.param_b)
print('----'*10)
plot = C()
print(plot.param_a)
print(plot.param_b)

['dummy_a']
None
----------------------------------------
['dummy_a']
----------------------------------------
['dummy_b']
----------------------------------------
['dummy_a']
['dummy_b']
```

I'm trying to build a dashboard (using panel) that's a composition of different dashboards that work individually and to do that I'm using class inheritances. As shown in the code snippet above When I first call `C` class due to the order of inits `param_b` is not being set to his default value and continues as `None`. Something weirder is that if we first call `A()` and `B()` then calling `C()` will not have that first behaviour. There is a way to avoid this behaviour?

**Comment by philippjfr** [comment]
Bit confused by your constructors, you should be calling the `super().__init__()`. I think that should resolve your issues.

**Comment by jbednar** [comment]
Also, you may have constructed the example just to match your real use case that's more complicated, but in general with Param you shouldn't use constructors at all unless you have a good reason. Very often the parameter machinery is sufficient for your construction needs, and it is much simpler to maintain and reason about, and that way you don't have to remember the `super()`.

E.g. here you should be able to simply redefine `param_a` in class `A` and supply a new default value and (I believe) a new objects list in the second declaration, without having to manipulate those things in the constructor.  The behavior should then follow the inheritance without any special work from you.

**Comment by philippjfr** [comment]
Going to close since this is a usage question.
