### ISSUE TITLE
The given default value, bounds and step are not respected

### ISSUE THREAD

**Issue by agiord** [pyviz/param#345]
Hello, this is my first issue on github. I am sorry if it is a repetition of a problem already encountered, but I have not found anything on this. It seems that the declared parameters (both Integers, or Magnitude, or else) do not respect the given default value, bounds and step: the resulting default value is always the lower bound set, furthermore the range of the parameter is always split into three steps.  
An example can be found here: https://nbviewer.jupyter.org/github/agiord/ibk_temp_plot/blob/master/problem_param.ipynb

The funny thing is that it worked just fine until this morning, then when I started to clean my code it stopped working, even for these minimal examples.
Thank you in advance for your time, and thanks also for this cool package!
Antonio

**Comment by jbednar** [comment]
I haven't been able to reproduce this problem with Panel 0.6:

![image](https://user-images.githubusercontent.com/1695496/58911027-90191200-86dc-11e9-8300-77df9059857d.png)
![image](https://user-images.githubusercontent.com/1695496/58911560-b55a5000-86dd-11e9-9667-b013f84856aa.png)

**Comment by agiord** [comment]
actually today it started to work normally again as @jbednar reports
